pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                echo 'Hello World'
                sh 'git --version'
                sh 'docker --version'
            }
        }
    }
}
